//****************************************************************************
// @Module        Asynchronous / Synchronous Serial Interface (ASC)
// @Filename      ASC.H
// @Project       v1.dav
//----------------------------------------------------------------------------
// @Controller    Infineon C164CI-8E
//
// @Compiler      KEIL C166
//
// @Codegenerator DAvE 2-0-0
//
// @Description   This file contains all function prototypes and macros for
//                the Asynchronous / Synchronous Serial Interface.
//
//----------------------------------------------------------------------------
// @Date          16.04.2018 09:39:21
//
//****************************************************************************

//****************************************************************************
// @Prototypes of global functions
//****************************************************************************

void ASC_vInit(void);
void ASC_vSendData(uword Data);


// USER CODE BEGIN (ASCHeader,1)

// USER CODE END


//****************************************************************************
// @Macros
//****************************************************************************


// USER CODE BEGIN (ASCHeader,2)

// USER CODE END


//***************************************************************************
// @Defines
//***************************************************************************


// USER CODE BEGIN (ASCHeader,4)

// USER CODE END


//****************************************************************************
// @Interrupt Vectors
//****************************************************************************



// USER CODE BEGIN (ASCHeader,3)

// USER CODE END


